### ISSUE TITLE
Support Lucee operators

### ISSUE THREAD

**Issue by KamasamaK** [cfparser/cfparser#128]
See [Lucee Operators](https://docs.lucee.org/guides/developing-with-lucee-server/operators.html).

Among those, the exclusive operators that do not seem to parse are `===`, `!==`, `CT`, and `NCT`.

**Comment by sbleon** [comment]
The string append operator `&=` also seems to cause problems:

```java.lang.NullPointerException
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitLocalAssignmentExpression(CFExpressionVisitor.java:174)
	at cfml.parsing.cfscript.walker.CFExpressionVisitor.visitLocalAssignmentExpression(CFExpressionVisitor.java:77)
	at cfml.CFSCRIPTParser$LocalAssignmentExpressionContext.accept(CFSCRIPTParser.java:5480)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:278)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:100)
	at cfml.CFSCRIPTParser$StatementContext.accept(CFSCRIPTParser.java:2352)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCompoundStatement(CFScriptStatementVisitor.java:254)
	at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitCompoundStatement(CFScriptStatementVisitor.java:100)
...
```

**Comment by sbleon** [comment]
My error (with `&=`), seems like it might be fixed in the `develop` branch: https://github.com/cfparser/cfparser/commit/435821dd68b21022a09fcfc99720c1cc44a71470

**Comment by KamasamaK** [comment]
That is not a Lucee-specific operator
