### ISSUE TITLE
NPE in for loop

### ISSUE THREAD

**Issue by ryaneberly** [cfparser/cfparser#87]
the following snippet from https://github.com/bennadel/POIUtility.cfc/blob/master/coldfusion_mx7/POIUtility.cfc#L804 cases a NPE

<cfscript>
	// Loop over each CSS pair.
	for (
		local.PairIterator = local.Pairs.Iterator() ;
		local.PairIterator.HasNext() ;
		){
	}
</cfscript>
java.lang.NullPointerException
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitForStatement(CFScriptStatementVisitor.java:310)
at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitForStatement(CFScriptStatementVisitor.java:95)
at cfml.CFSCRIPTParser$ForStatementContext.accept(CFSCRIPTParser.java:2883)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:256)
at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitStatement(CFScriptStatementVisitor.java:95)
at cfml.CFSCRIPTParser$StatementContext.accept(CFSCRIPTParser.java:2239)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
at cfml.CFSCRIPTParserBaseVisitor.visitElement(CFSCRIPTParserBaseVisitor.java:41)
at cfml.CFSCRIPTParser$ElementContext.accept(CFSCRIPTParser.java:485)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
at cfml.CFSCRIPTParserBaseVisitor.visitScriptBlock(CFSCRIPTParserBaseVisitor.java:20)
at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:103)
at cfml.parsing.cfscript.walker.CFScriptStatementVisitor.visitScriptBlock(CFScriptStatementVisitor.java:95)
at cfml.CFSCRIPTParser$ScriptBlockContext.accept(CFSCRIPTParser.java:254)
at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
at cfml.parsing.CFMLParser.parseScript(CFMLParser.java:480)
at com.cflint.CFLint.process(CFLint.java:441)
at com.cflint.CFLint.processStack(CFLint.java:323)
at com.cflint.CFLint.process(CFLint.java:296)
at com.cflint.CFLint.scan(CFLint.java:250)
at com.cflint.CFLint.scan(CFLint.java:176)
at com.cflint.main.CFLintMain.execute(CFLintMain.java:436)
at com.cflint.main.CFLintMain.main(CFLintMain.java:282)

**Comment by ryaneberly** [comment]
https://github.com/cflint/CFLint/issues/408
